package Interfaz;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.Normalizer;

import Modelo.CarritoCompra;
import Modelo.Catalogo;
import Control.Producto;
import Control.ItemsCompra;
import Conexion.Conexion;
public class Compra extends javax.swing.JFrame {

    
    
    public Compra() {
        initComponents();
        cargarProductos();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Reponer Stock");
        setBounds(225,100,1075,570);
        setResizable(false);
        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }
});
    }
    DefaultTableModel modelo = new DefaultTableModel(
            new Object[]{"ID", "Nombre", "Precio", "Cantidad","Subtotal"},0
    );
    private CarritoCompra carrito = new CarritoCompra();
    
    private String quitarAcentos(String texto){
        if (texto == null) return null;
        String normalizado = Normalizer.normalize(texto, Normalizer.Form.NFD);
        return normalizado.replaceAll("\\p{M}", "");
    }
    private void buscarProducto() {
    String nombreBusqueda = quitarAcentos(txtproducto.getText().trim().toLowerCase());

    DefaultTableModel modelo = (DefaultTableModel) tblproductos.getModel();
    modelo.setRowCount(0); // limpia la tabla antes de mostrar resultados

    Catalogo catalogo = new Catalogo();
    java.util.Vector<Producto> lista = catalogo.mostrar();

    for (Producto p : lista) {
        String nombreProducto = quitarAcentos(p.getNombre().toLowerCase());
        if (nombreProducto.contains(nombreBusqueda)) {
            modelo.addRow(new Object[]{
                p.getId(),      // o p.codigo según tu clase
                p.getNombre(),
                p.getPrecio(),
                p.getCategoria(),
                p.getStock()
            });
        }
    }
}

    
    
    private void refreshTabla() {
    DefaultTableModel modelo = (DefaultTableModel) tbllista.getModel();
    modelo.setRowCount(0);
    for (ItemsCompra item : carrito.getItems()) {
        modelo.addRow(new Object[]{
            item.getProducto().getId(),
            item.getProducto().getNombre(),
            item.getProducto().getPrecio(),
            item.getCantidad(),
            item.getSubtotal()
        });
    }
    ltotal.setText(String.valueOf(carrito.getTotalCompra()));
}

    
    
    private void agregarAlCarrito(Producto producto, int cantidad) {
        if (producto == null || cantidad <= 0) return;
        carrito.agregarProducto(producto, cantidad);
        refreshTabla();
    }
    
    
    
    private void cargarProductos() {
    DefaultTableModel modelo = (DefaultTableModel) tblproductos.getModel();
    modelo.setRowCount(0);

    Catalogo catalogo = new Catalogo();
    java.util.Vector<Control.Producto> lista = catalogo.mostrar();

    for (Control.Producto p : lista) {
        modelo.addRow(new Object[]{
            p.codigo,      // o p.getId() si lo cambiaste
            p.nombre,
            p.precio,
            p.categoria,
            p.stock
        });
    }
}
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelcompras = new javax.swing.JPanel();
        bquitar = new javax.swing.JButton();
        bagregar = new javax.swing.JButton();
        ltotalp = new javax.swing.JLabel();
        ltotal = new javax.swing.JLabel();
        bvaciar = new javax.swing.JButton();
        bconfirmar = new javax.swing.JButton();
        txtcantidad = new javax.swing.JTextField();
        labelcantidad = new javax.swing.JLabel();
        ltitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelproductos = new javax.swing.JLabel();
        lproducto = new javax.swing.JLabel();
        txtproducto = new javax.swing.JTextField();
        bbuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproductos = new javax.swing.JTable();
        blimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelcarrito = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbllista = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelcompras.setBackground(new java.awt.Color(97, 97, 97));

        bquitar.setBackground(new java.awt.Color(38, 58, 160));
        bquitar.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        bquitar.setText("Quitar");
        bquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bquitarActionPerformed(evt);
            }
        });

        bagregar.setBackground(new java.awt.Color(38, 58, 160));
        bagregar.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        bagregar.setText("Agregar");
        bagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagregarActionPerformed(evt);
            }
        });

        ltotalp.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        ltotalp.setText("TOTAL A PAGAR");

        ltotal.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        ltotal.setText("0.0");

        bvaciar.setBackground(new java.awt.Color(38, 58, 160));
        bvaciar.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        bvaciar.setText("Vaciar");
        bvaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bvaciarActionPerformed(evt);
            }
        });

        bconfirmar.setBackground(new java.awt.Color(38, 58, 160));
        bconfirmar.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        bconfirmar.setText("Confirmar");
        bconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bconfirmarActionPerformed(evt);
            }
        });

        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });

        labelcantidad.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        labelcantidad.setText("CANTIDAD:");

        ltitulo.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        ltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltitulo.setText("REGISTRAR COMPRAS ");

        jPanel1.setBackground(new java.awt.Color(38, 58, 160));

        labelproductos.setBackground(new java.awt.Color(38, 70, 200));
        labelproductos.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        labelproductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelproductos.setText("PRODUCTOS");
        labelproductos.setOpaque(true);

        lproducto.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        lproducto.setText("Producto:");

        txtproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtproductoKeyTyped(evt);
            }
        });

        bbuscar.setBackground(new java.awt.Color(38, 58, 160));
        bbuscar.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        bbuscar.setText("Buscar");
        bbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuscarActionPerformed(evt);
            }
        });

        tblproductos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tblproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cod producto", "Nombre", "Precio", "Categoria", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblproductos);

        blimpiar.setBackground(new java.awt.Color(38, 58, 160));
        blimpiar.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        blimpiar.setText("Limpiar");
        blimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lproducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(labelproductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelproductos)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbuscar)
                    .addComponent(blimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(38, 58, 160));

        labelcarrito.setBackground(new java.awt.Color(38, 70, 200));
        labelcarrito.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        labelcarrito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelcarrito.setText("CARRITO ");
        labelcarrito.setOpaque(true);

        tbllista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cod producto", "Nombre", "Precio", "Cantidad", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbllista);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelcarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(labelcarrito)
                .addGap(80, 80, 80)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelcomprasLayout = new javax.swing.GroupLayout(panelcompras);
        panelcompras.setLayout(panelcomprasLayout);
        panelcomprasLayout.setHorizontalGroup(
            panelcomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcomprasLayout.createSequentialGroup()
                .addComponent(ltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelcomprasLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(panelcomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcomprasLayout.createSequentialGroup()
                        .addComponent(ltotalp)
                        .addGap(18, 18, 18)
                        .addComponent(ltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelcomprasLayout.createSequentialGroup()
                        .addGroup(panelcomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelcomprasLayout.createSequentialGroup()
                                .addComponent(labelcantidad)
                                .addGap(18, 18, 18)
                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bagregar))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(panelcomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcomprasLayout.createSequentialGroup()
                                .addComponent(bquitar)
                                .addGap(28, 28, 28)
                                .addComponent(bvaciar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bconfirmar)
                                .addGap(36, 36, 36))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 26, Short.MAX_VALUE))))
        );
        panelcomprasLayout.setVerticalGroup(
            panelcomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcomprasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ltitulo)
                .addGap(49, 49, 49)
                .addGroup(panelcomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelcomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcomprasLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelcomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelcantidad)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bagregar)
                            .addComponent(bconfirmar)))
                    .addGroup(panelcomprasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelcomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bquitar)
                            .addComponent(bvaciar))))
                .addGap(18, 18, 18)
                .addGroup(panelcomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ltotalp)
                    .addComponent(ltotal))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelcompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelcompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bquitarActionPerformed
        int fila = tbllista.getSelectedRow();
        if (fila == -1) {
                JOptionPane.showMessageDialog(this, "Seleccione un producto del carrito.");
            return;
        }

        int idProducto = (int) tbllista.getValueAt(fila, 0);
        carrito.quitarProducto(idProducto);
        refreshTabla();
    }//GEN-LAST:event_bquitarActionPerformed

    private void bagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagregarActionPerformed
        if(txtcantidad.getText().equals("0")){
             JOptionPane.showMessageDialog(this,"Cantidad invalida.");
             return;
        }
        int fila = tblproductos.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto.");
            return;
        }

        int id = (int) tblproductos.getValueAt(fila, 0);
        String nombre = tblproductos.getValueAt(fila, 1).toString();
        double precio = Double.parseDouble(tblproductos.getValueAt(fila, 2).toString());

        int cantidad;
        try {
            cantidad = Integer.parseInt(txtcantidad.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cantidad inválida.");
            return;
        }

        Producto p = new Producto();
        p.setId(id);
        p.setNombre(nombre);
        p.setPrecio(precio);
        carrito.agregarProducto(p, cantidad);

        refreshTabla();
        
        ltotal.setText(String.valueOf(carrito.getTotalCompra()));
        // TODO add your handling code here:
    }//GEN-LAST:event_bagregarActionPerformed

    private void bvaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bvaciarActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
        "Seguro que desea vaciar carrito?",
        "Confirmar",
        JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
            carrito.limpiar();
            refreshTabla();
            ltotal.setText("0.0");
            txtcantidad.setText("");
        }        
        // TODO add your handling code here:
    }//GEN-LAST:event_bvaciarActionPerformed

    private void bbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuscarActionPerformed
        buscarProducto();
        // TODO add your handling code here:
    }//GEN-LAST:event_bbuscarActionPerformed

    private void bconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bconfirmarActionPerformed
        if (carrito.getItems().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "El carrito está vacío. Agregue productos antes de confirmar.",
                    "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this,
        "Esta seguro de confirmar la compra?",
        "Confirmar",
        JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
        double total = carrito.getTotalCompra();
        
        try(Connection con = Conexion.getConnection()){
            String sqlc = "INSERT INTO compras (fecha,total)VALUES (NOW(),?)";
            PreparedStatement psc = con.prepareStatement(sqlc, Statement.RETURN_GENERATED_KEYS);
            psc.setDouble(1, total);
            psc.executeUpdate();
            
            ResultSet rs = psc.getGeneratedKeys();
            int idcompra=0;
            if(rs.next()){
                idcompra = rs.getInt(1);
            }
            
            String sqld = "INSERT INTO detalle_compra (id_compra,id_producto,cantidad,precio,subtotal)VALUES(?,?,?,?,?)";
            PreparedStatement psd = con.prepareStatement(sqld);
            
            for (ItemsCompra item : carrito.getItems()) {
                psd.setInt(1, idcompra);
                psd.setInt(2, item.getProducto().getId());
                psd.setInt(3, item.getCantidad());
                psd.setDouble(4, item.getProducto().getPrecio());
                psd.setDouble(5, item.getSubtotal());
                psd.executeUpdate();
            }
            
            String sqls = "UPDATE productos SET stock = stock + ? where id_producto = ?";
            PreparedStatement pss = con.prepareStatement(sqls);
            
            for (ItemsCompra item : carrito.getItems()) {
                pss.setInt(1, item.getCantidad());
                pss.setInt(2, item.getProducto().getId());
                pss.executeUpdate();
            }
            carrito.limpiar();
            refreshTabla();
            cargarProductos();
            txtcantidad.setText("");
            txtproducto.setText("");
            JOptionPane.showMessageDialog(this, "Compra registrada correctamente.");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error al registrar la compra: " + e.getMessage());
    }
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_bconfirmarActionPerformed

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped
        if(txtcantidad.getText().length() >= 2){
            evt.consume();
        }
    }//GEN-LAST:event_txtcantidadKeyTyped

    private void txtproductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtproductoKeyTyped
        if(txtproducto.getText().length()>30){
            evt.consume();
        }
    }//GEN-LAST:event_txtproductoKeyTyped

    private void blimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blimpiarActionPerformed
        txtproducto.setText("");
        cargarProductos();
    }//GEN-LAST:event_blimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagregar;
    private javax.swing.JButton bbuscar;
    private javax.swing.JButton bconfirmar;
    private javax.swing.JButton blimpiar;
    private javax.swing.JButton bquitar;
    private javax.swing.JButton bvaciar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelcantidad;
    private javax.swing.JLabel labelcarrito;
    private javax.swing.JLabel labelproductos;
    private javax.swing.JLabel lproducto;
    private javax.swing.JLabel ltitulo;
    private javax.swing.JLabel ltotal;
    private javax.swing.JLabel ltotalp;
    private javax.swing.JPanel panelcompras;
    private javax.swing.JTable tbllista;
    private javax.swing.JTable tblproductos;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtproducto;
    // End of variables declaration//GEN-END:variables
}